### ISSUE TITLE
add list of reps to /people

### ISSUE THREAD

**Issue by irvin** [irvin/reps-portal-static-archive#1]
need to add reps list from https://reps.mozilla.org/people/#/ to https://github.com/irvin/reps-portal-static-archive/blob/master/people/index.html

**Comment by Ryuno-Ki** [comment]
Looking at network traffic, I can see API calls to https://reps.mozilla.org/api/v1/rep/?order_by=-profile__date_joined_program&offset=<number>&limit=<number>

The response contains links to previous and next endpoints in the `meta` field.
Perhaps crawling those first and rebuild the markup in a second step?

**Comment by irvin** [comment]
a manual save of this page could work (and perhaps easier?) 
https://reps.mozilla.org/people/#/view/list/

we already had data stored in [this repo](https://github.com/mozilla/reps-archive).

**Comment by irvin** [comment]
resolved with dc6366a6c84d186e6c09f1c8898ec18663379f87
